[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/:merk/product/:slug"
  to = "/product.html"
  status = 200

[[redirects]]
  from = "/:merk/:soort/:fase"
  to = "/subpage.html"
  status = 200

[[redirects]]
  from = "/:merk/:soort"
  to = "/subpage.html"
  status = 200

[[redirects]]
  from = "/:merk"
  to = "/subpage.html"
  status = 200
